export const i18n = {
  en: {
    lang: 'Language', upload: 'Upload file as AI context', remove: 'Remove uploaded file', removeObs: 'Remove observation row', random: 'Generate random test data', review: 'Review record', export: 'Export as PDF', working: 'Working...', server: 'Server', title: 'AI-Assisted Clinical Evaluation System for Maritime Nursing', subtitle: 'Digital Radio Medical Record for simulation training', brand: 'Danish Maritime Authority', brandSub: 'Digital Radio Medical Record', rmr: 'Radio Medical Record', details: 'Patient and ship details', problem: 'Problem description', problemPh: 'What happened, where, when, and what are the patient symptoms?', airway: 'A: Airway', breathing: 'B: Breathing', circulation: 'C: Circulation', disability: 'D: Disability', expose: 'E: Expose', obs: 'Observation chart', addObs: 'Add observation row', findings: 'Clinical documentation findings', score: 'Score', advice: 'AI-generated advice and next actions', conn: 'Connection/API message', fileUsed: 'Uploaded document context is active', select: '--', yes: 'Yes', no: 'No', unknown: 'unknown', english: 'English', danish: 'Danish', contextPreview: 'Extracted AI context preview', pdfNote: 'The uploaded document text will be used by the review and included in the exported report.'
  },
  da: {
    lang: 'Sprog', upload: 'Upload fil som AI-kontekst', remove: 'Fjern uploadet fil', removeObs: 'Fjern observationsrække', random: 'Generér tilfældige testdata', review: 'Gennemgå journal', export: 'Eksportér som PDF', working: 'Arbejder...', server: 'Server', title: 'AI-understøttet klinisk evalueringssystem for maritim sygepleje', subtitle: 'Digital Radio Medical Record til simulationstræning', brand: 'Søfartsstyrelsen', brandSub: 'Digital Radio Medical Record', rmr: 'Radio Medical Record', details: 'Patient- og skibsoplysninger', problem: 'Problembeskrivelse', problemPh: 'Hvad er der sket, hvor, hvornår, og hvilke symptomer har patienten?', airway: 'A: Luftvej', breathing: 'B: Vejrtrækning', circulation: 'C: Kredsløb', disability: 'D: Neurologisk status', expose: 'E: Eksponering', obs: 'Observationsskema', addObs: 'Tilføj observationsrække', findings: 'Kliniske dokumentationsfund', score: 'Score', advice: 'AI-genererede råd og næste handlinger', conn: 'Forbindelse/API-besked', fileUsed: 'Uploadet dokumentkontekst er aktiv', select: '--', yes: 'Ja', no: 'Nej', unknown: 'ukendt', english: 'Engelsk', danish: 'Dansk', contextPreview: 'Udtrukket AI-kontekst', pdfNote: 'Den uploadede dokumenttekst bruges i gennemgangen og medtages i den eksporterede rapport.'
  }
};

export const fieldLabels = {
  en: { name_title: 'Name / title', birthdate_cpr: 'Birthdate / CPR', gender: 'Gender', nationality: 'Nationality', date: 'Date', utc: 'UTC', shipping_company: 'Shipping company', ship_name: 'Ship name', ship_email: 'Ship e-mail', satellite_call_no: 'Satellite call no.', call_signal: 'Call signal', coordinates: 'Coordinates', destination_eta: 'Destination/ETA', nearest_port_eta: 'Nearest port and ETA', medicine_chest: 'Medicine chest', page: 'Page', has_allergies: 'Does the patient have allergies?', allergies_details: 'If so, which one(s)?', takes_medicine: 'Does the patient take medicine?', medicine_details: 'If so, which one(s)?', clear: 'Clear airways', jaw: 'Jaw lift', suction: 'Suction applied', guedel: 'Guedel® airway', cpr: 'CPR initiated at', oxygen: 'Oxygen administered l/min', oxygenMethod: 'Oxygen method', injury: 'Neck/back injury suspected', fast: 'Fast', slow: 'Slow', shallow: 'Shallow', deep: 'Deep', normal: 'Normal', other: 'Other', breaths: 'Breaths/min normal 12-16', spo2: 'Oxygen saturation % normal 95-100', cap: 'Capillary response seconds', cannula: 'Venous cannula inserted', skinColor: 'Skin color', skinFeel: 'How does the skin feel?', pulse: 'Pulse/min normal 60-80', measured: 'Measured at', sys: 'Blood pressure systolic 120-140', dia: 'Blood pressure diastolic 60-90', loc: 'Level of consciousness', conv: 'Convulsions', para: 'Paralysis', pupil: 'Pupil reaction normal', pupilDesc: 'Describe pupil findings', top: 'Top to toe examination performed', hypo: 'Hypothermia/overheating signs checked', tempMeasured: 'Temperature measured', tempMouth: 'Temperature mouth', altTemp: 'Alternative temperature', where: 'Where', injuryFind: 'Signs of injury/illness findings', hypoFind: 'Hypothermia/overheating findings', actions: 'Performed actions not described above', meds: 'Medication before contact to Radio Medical', time1: 'Time 1', time2: 'Time 2', time3: 'Time 3', time4: 'Time 4', officer: 'Medical officer name/title' },
  da: { name_title: 'Navn / titel', birthdate_cpr: 'Fødselsdato / CPR', gender: 'Køn', nationality: 'Nationalitet', date: 'Dato', utc: 'UTC', shipping_company: 'Rederi', ship_name: 'Skibsnavn', ship_email: 'Skibs-e-mail', satellite_call_no: 'Satellittelefon', call_signal: 'Kaldesignal', coordinates: 'Koordinater', destination_eta: 'Destination/ETA', nearest_port_eta: 'Nærmeste havn og ETA', medicine_chest: 'Medicinkiste', page: 'Side', has_allergies: 'Har patienten allergier?', allergies_details: 'Hvis ja, hvilke?', takes_medicine: 'Tager patienten medicin?', medicine_details: 'Hvis ja, hvilken?', clear: 'Fri luftvej', jaw: 'Kæbeløft', suction: 'Sug anvendt', guedel: 'Guedel® airway', cpr: 'CPR startet kl.', oxygen: 'Ilt givet l/min', oxygenMethod: 'Iltmetode', injury: 'Mistanke om nakke-/rygskade', fast: 'Hurtig', slow: 'Langsom', shallow: 'Overfladisk', deep: 'Dyb', normal: 'Normal', other: 'Andet', breaths: 'Vejrtrækninger/min normal 12-16', spo2: 'Iltmætning % normal 95-100', cap: 'Kapillærrespons sekunder', cannula: 'Venekanyle anlagt', skinColor: 'Hudfarve', skinFeel: 'Hvordan føles huden?', pulse: 'Puls/min normal 60-80', measured: 'Målt ved', sys: 'Systolisk blodtryk 120-140', dia: 'Diastolisk blodtryk 60-90', loc: 'Bevidsthedsniveau', conv: 'Kramper', para: 'Lammelse', pupil: 'Normal pupilreaktion', pupilDesc: 'Beskriv pupilfund', top: 'Top-til-tå-undersøgelse udført', hypo: 'Tegn på hypotermi/overophedning kontrolleret', tempMeasured: 'Temperatur målt', tempMouth: 'Temperatur i munden', altTemp: 'Alternativ temperatur', where: 'Hvor', injuryFind: 'Fund ved skade/sygdom', hypoFind: 'Fund ved hypotermi/overophedning', actions: 'Udførte handlinger ikke beskrevet ovenfor', meds: 'Medicin givet før kontakt til Radio Medical', time1: 'Tid 1', time2: 'Tid 2', time3: 'Tid 3', time4: 'Tid 4', officer: 'Medical Officer navn/titel' }
};

export const obsLabels = {
  en: { date: 'Date', time: 'Time', general_condition: 'General condition', consciousness_level: 'Level of consciousness', oxygen_l_min: 'Oxygen liters/min', breathing_rate: 'Breathing frequency/min', capillary_response_seconds: 'Capillary response sec.', oxygen_saturation: 'Oxygen saturation %', heart_rate: 'Heart rate/min', blood_pressure: 'Blood pressure', temperature_mouth: 'Mouth temperature', pupil_reaction: 'Pupil reaction', venous_cannula_inserted: 'Venous cannula inserted', intravenous_fluid_drops_min: 'IV fluid drops/min', fluid_intake_drink: 'Fluid intake/drink', urine_24h: '24-hour urine', urine_sticks: 'Urine sticks', blood_sugar: 'Blood sugar', malaria_test: 'Malaria test', crp_test: 'CRP test' },
  da: { date: 'Dato', time: 'Tid', general_condition: 'Almentilstand', consciousness_level: 'Bevidsthedsniveau', oxygen_l_min: 'Ilt liter/min', breathing_rate: 'Respirationsfrekvens/min', capillary_response_seconds: 'Kapillærrespons sek.', oxygen_saturation: 'Iltmætning %', heart_rate: 'Hjertefrekvens/min', blood_pressure: 'Blodtryk', temperature_mouth: 'Temperatur i munden', pupil_reaction: 'Pupilreaktion', venous_cannula_inserted: 'Venekanyle anlagt', intravenous_fluid_drops_min: 'IV-væske dråber/min', fluid_intake_drink: 'Væskeindtag/drikke', urine_24h: '24-timers urin', urine_sticks: 'Urinstix', blood_sugar: 'Blodsukker', malaria_test: 'Malariatest', crp_test: 'CRP-test' }
};
